<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Store Dashboard Translations
    |--------------------------------------------------------------------------
     */
    /*Notifications */
    'orderAcceptedNotification' => 'Commande acceptée.',
    'successNotification' => 'Succès 👌',
    'orderSomethingWentWrongNotification' => 'Une erreur s\'est produite ou la commande a déjà été acceptée / annulée.',
    'woopssNotification' => 'Wooopsss ⚠️',
    'orderCanceledNotification' => 'Commande annulée',

    /* GENERAL */
    'total' => 'TOTAL',
    'sphResultFor' => 'Résultats pour',
    'edit' => 'Éditer',
    'save' => 'Sauvegarder',
    'update' => 'Mettre à jour',

    /* NAV BAR */
    'navLogout' => 'Se déconnecter',
    'navStores' => 'Magasins',
    'navItemsMenu' => 'Articles et Menu',
    'navSubAddonCat' => 'Catégories d\'addons',
    'navSubAddon' => 'Addons',
    'navSubMenuCat' => 'Catégories de menu',
    'navSubItems' => 'Articles',
    'navOrders' => 'Commandes',
    'navEarnings' => 'Revenus',

    /* Dashboard Page */
    'dashboardTitle' => 'Tableau de bord',
    'dashboardStores' => 'Magasins',
    'dashboardOrdersProcessed' => 'Commandes traitées',
    'dashboardItemsSold' => 'Articles vendus',
    'dashboardEarnings' => 'Revenus',

    'dashboardNewOrders' => 'Nouvelles commandes',
    'dashboardOrderID' => 'numéro de commande',
    'dashboardStore' => 'Magasin',
    'dashboardPrice' => 'Prix',
    'dashboardOrderStatus' => 'Statut de la commande',
    'dashboardAcceptOrder' => 'Accepter la commande',
    'dashboardCancelOrder' => 'annuler la commande',
    'dashboardDoubleClickMsg' => 'Double-cliquez pour annuler',
    'dashboardNew' => 'NOUVEAU',
    'dashboardSelfPickup' => 'Emporté',
    'dashboardNoOrders' => 'Aucune commande à afficher',

    'dashboardPreparingOrders' => 'Préparation des commandes',
    'dashboardOrderPlacedTime' => 'Order Placed Time',
    'dashboardOrderAcceptedTime' => 'Order Accepted Time',
    'dashboardMarkAsReady' => 'Marquer comme prêt',
    'dashboardMarkAsCompleted' => 'Marquer comme terminé',

    /* Stores Page */
    'spPageTitle' => 'Magasins - Tableau de bord',
    'spAddNewStoreBtn' => 'Ajouter un nouveau magasin',
    'spTableID' => 'ID',
    'spTableImage' => 'Image',
    'spTableName' => 'Nom',
    'spTableAddress' => 'Adresse',
    'spTableStatus' => 'Status',
    'spTableCA' => 'Créé à',
    'spRowPending' => 'En attente',
    'spRowActive' => 'Actif',
    'spRowInActive' => 'Inactif',

    'seLblStoreName' => 'Nom du magasin',
    'sePhStoreName' => 'Nom du magasin',
    'seLblDescription' => 'Description',
    'sePhDescription' => 'Description courte du magasin',
    'seLblImage' => 'Image',
    'sePhImage' => 'Dimension de l\'image 160x117',
    'seLblApproxDeliveryTime' => 'Délai de livraison approximatif',
    'sePhApproxDeliveryTime' => 'Temps en minutes',
    'seLblApproxPriceForTwo' => 'Prix approximatif pour deux',
    'sePhApproxPriceForTwo' => 'Prix approximatif pour 2 personnes en',
    'seLblFullAddress' => 'Adresse complète',
    'sePhFullAddress' => 'Adresse complète du magasin',
    'seLblPincode' => 'Code Postal',
    'seToolTipPincode' => 'Code postal du magasin',
    'seLblLandMark' => 'Repère',
    'sePhLandMark' => 'Tout repère à proximité',
    'seLblLat' => 'Latitude',
    'seLblLong' => 'Longitude',
    'sePhTextLatLong1' => 'Vous pouvez utiliser des services tels que:',
    'sePhTextLatLong2' => 'Si vous entrez une latitude / longitude non valide, le système de carte peut planter avec un écran blanc.',
    'seLblCertificate' => 'RCCM/Licence/Patente',
    'sePhCertificate' => 'Code de certificat ou code de licence',
    'seLblStoreCharge' => 'Frais de magasin (emballage / extra)',
    'sePhStoreCharge' => 'Store Charge in ',
    'seLblPureVeg' => 'Pure Veg?',
    'seLblMinOrderPrice' => 'Prix minimum de la commande',
    'seLblAutomaticScheduling' => 'Planification automatique',
    'sePhMinOrderPrice' => 'Valeur minimale du panier avant remise et taxe en',
    'sePageTitleEditing' => 'Édition',
    'sePageTitleStoreDetails' => 'Détails du magasin',
    'seDisable' => 'Fermer',
    'seEnable' => 'Ouvrir',
    'seStoreSchedulingTimes' => 'Horaires',
    'seSunday' => 'Dimance',
    'seMonday' => 'Lundi',
    'seTuesday' => 'Mardi',
    'seWednesday' => 'Mercredi',
    'seThursday' => 'Jeudi',
    'seFriday' => 'Vendredi',
    'seSaturday' => 'Samedi',
    'seOpeningTime' => 'Horaire d\'ouverture',
    'seClosingTime' => 'Heure de fermeture',
    'seRemoveTimeSlot' => 'Supprimer',
    'seAddSlot' => 'Ajouter',
    'seScheduleUpdateMsg' => 'Assurez-vous que l\'heure de fermeture est toujours supérieure à l\'heure d\'ouverture',

    /* Addon Categories Page */

    'addonCategoriesTitle' => 'Addon Categories - Dashboard',
    'btnAddNewCat' => 'Add New Addon Category',
    'acpSearchPlaceHolder' => 'Search with addon category name',
    'acpTableName' => 'Nom',
    'acpTableType' => 'Type',
    'acpTableNOA' => 'No. Of Addons',
    'acpTableCA' => 'Créé à',
    'acpRowSingleSelection' => 'Sélection unique',
    'acpRowMultipleSelection' => ' Sélection multiple',
    'acpInputName' => 'Addon Category Name',
    'acpEditTitle' => 'Édition',
    'acpEditTitleAd' => 'Addon Category Details',

    /* Addons Page */

    'addonPageTitle' => 'Addons - Dashboard',
    'btnAddNewAddon' => 'Add New Addon',
    'apSearchPlaceHolder' => 'Search with addon name',
    'apTableName' => 'Nom',
    'apTablePrice' => 'Prix',
    'apTableAddonCategory' => 'Addon Category',
    'apTableCreatedAt' => 'Créé à',
    'apInputName' => 'Addon Name',
    'apInputNamePH' => 'Addon Name',
    'apInputPrice' => 'Prix',
    'apInputPricePH' => 'Addon Price in',
    'apInputAddonCategory' => "Addon's Category",
    'apePagetitle' => 'Edit Addon - Dashboard',
    'apeTitleEditing' => 'Édition',
    'apeTitleDetails' => 'Addon Details',
    'apeLabelName' => 'Addon Name',
    'apePlaceHolderName' => 'Addon Name',
    'apeLabelPrice' => 'Prix',
    'apePlaceHolderPrice' => 'Addon Price in',

    /* Menu Categories Page */

    'mcpPageTitle' => 'Catégories d\'articles - Tableau de bord',
    'mcpAddNewCatBtn' => 'Ajouter une nouvelle catégorie',
    'mcpTableCatId' => 'ID catégorie',
    'mcpTableName' => 'Nom',
    'mcpTableNOI' => 'Nombre d\'articles',
    'mcpTableStatus' => 'Status',
    'mcpTableCA' => 'Créé à',
    'mcpModalTitle' => 'Ajouter une nouvelle catégorie d\'article',
    'mcpModalLabelName' => 'Nom',
    'mcpModalPlaceHolderName' => 'Entrez le nom de la catégorie',
    'mcpEnabled' => 'Activé',
    'mcpDisabled' => 'Désactivé',

    /* Items Page */

    'ipPageTitle' => 'Articles - Tableau de bord',
    'ipAddNewItemBtn' => 'Ajouter un nouvel article',
    'ipBulkCsvUpload' => 'Téléchargement CSV en masse',
    'ipSearchPH' => 'Rechercher avec le nom de l\'article',
    'ipTableImage' => 'Image',
    'ipTableName' => 'Nom',
    'ipTableItemRestaurant' => "Item's Store",
    'ipTableItemCategory' => "Catégorie de l'article",
    'ipTablePrice' => 'Prix',
    'ipTableAttributes' => 'Les attributs',
    'ipTableCA' => 'Créé à',
    'ipRowRecommended' => 'Recommandé',
    'ipRowPopular' => 'Populaire',
    'ipRowNew' => 'Nouveau',
    'ipmTitle' => 'Ajouter un nouvel article',
    'ipmLabelName' => 'Nom de l\'article',
    'ipmPhName' => 'Nom de l\'article',
    'ipmLabelDescription' => 'Description de l\'article',
    'ipmPhDescription' => 'Description de l\'article',
    'ipmLabelMarkPrice' => 'Mark Price',
    'ipmMarkPriceToolTip' => 'Laissez ce champ vide ou nul(0) s\'il n\'est pas obligatoire',
    'ipmLabelSellingPrice' => 'Prix de vente',
    'ipmOldPricePh' => 'Prix de l\'article en',
    'ipmLabelPrice' => 'Prix',
    'ipmAddDiscountBtn' => 'Ajouter un prix promo',
    'ipmLabelItemRestaurant' => "Item's Store",
    'ipmLabelItemCategory' => "Catégorie de l'objet",
    'ipmLabelAddonCategory' => "Addon's Category",
    'ipmLabelImage' => 'Image',
    'ipmImageHelperText' => 'Dimension de l\'image 486x355',
    'ipmLabelIsRecommended' => 'Est recommandé?',
    'ipmLabelIsPopular' => 'Est populaire?',
    'ipmLabelIsNew' => 'Est nouveau?',
    'ipmLabelIsVeg' => 'Est Veg?',
    'ipmCsvTitle' => 'Téléchargement groupé en CSV pour les articles',
    'ipmLabelCsvFile' => 'Fichier CSV',
    'ipmBtnCsvDownloadSample' => 'Télécharger un exemple de CSV',
    'ipmBtnCsvUpload' => 'Télécharger',
    'ipePageTitle' => 'Article - Tableau de bord',
    'ipeEditing' => 'Édition',
    'ipeItemDetails' => 'Détails de l\'article',
    'ipeDisable' => 'Désactiver',
    'ipeEnable' => 'Activer',

    /* Orders Page */
    'opTitle' => 'Commandes - Tableau de bord',
    'opSearchPh' => 'Recherche avec ID de commande ...',
    'opTableOrderId' => 'numéro de commande',
    'opTableRestName' => 'Nom du marchand',
    'opTableStatus' => 'Status',
    'opTableTotal' => 'Total',
    'opTableCoupon' => 'Coupon',
    'opTableOrderPlacedAt' => 'Commande passée à',
    'opOrderStatus1' => 'Commande passée',
    'opOrderStatus2' => 'Commande acceptée',
    'opOrderStatus3' => 'Livraison attribuée',
    'opOrderStatus4' => 'Recupéré',
    'opOrderStatus5' => 'Complété',
    'opOrderStatus6' => 'Annulé',
    'opOrderStatus7' => 'Prêt à recupérer',
    'opDeliveryBy' => 'Livré par',
    'opNone' => 'AUCUN',
    'opView' => 'Consulter',
    'ovTitle' => 'Afficher la commande - Tableau de bord',
    'ovPrint' => 'Imprimer',
    'ovOrderPlaced' => 'Commande passée',
    'ovCustomerDetails' => 'Détails du client',
    'ovName' => 'Nom',
    'ovEmail' => 'Email',
    'ovContactNumber' => 'Numéro de contact',
    'ovStoreName' => 'Nom du magasin',
    'ovAddress' => 'Adresse',
    'ovPaymentMode' => 'Mode de paiement',
    'ovCommentSuggestion' => 'Commentaire/Suggestion',
    'ovTableCategory' => 'Catégorie',
    'ovTableAddon' => 'Addon',
    'ovTablePrice' => 'Prix',
    'ovCoupon' => 'Coupon',
    'ovStoreCharge' => 'Frais marchand',
    'ovDeliveryCharge' => 'Frais de livraison',
    'ovTax' => 'Taxe',
    'ovTotal' => 'Total',
    'ovAccept' => 'Accepter la commande',
    'ovTooltipCancel' => 'Double-cliquez pour annuler',
    'ovCancel' => 'annuler la commande',
    'ovMarkAsReady' => 'Marquer comme prêt',
    'ovMarkAsCompleted' => 'Marquer comme terminé',

    /* Earnings Page */

    'epTitle' => 'Revenus et paiements - Tableau de bord',
    'epSelectStore' => 'Sélectionnez un magasin',
    'epSelect' => 'Sélectionner',
    'epNetEarningsBeforeCommission' => 'Bénéfice net avant commission',
    'epYourBalanceAfterCommission' => 'Votre solde (après commission de',
    'epTotalValueBeforeCommission' => 'Valeur totale de vos ventes, avant commission',
    'epRequestPayout' => 'Demande de paiement',
    'epYourCurrentBalance' => 'Votre solde actuel est',
    'epReqPayoutMessage' => 'Vous serez admissible à un paiement lorsque le montant de votre solde dépassera',
    'epYourRequest' => 'Vous demandez un paiement de',
    'epSendRequest' => 'Envoyer une demande',
    'epCancelReq' => 'Annuler',
    'epRequestPayouts' => 'Paiements demandés',
    'epTableAmount' => 'Montant',
    'epTableStatus' => 'Status',
    'epTableTransactionMode' => 'Mode de transaction',
    'epTableTransactionID' => 'ID de transaction',
    'epTableMessage' => 'Message',
    'epTableCreated' => 'Créé',
    'epTableUpdated' => 'Mise à jour',

    /* Version 2.3.0 */
    'opPaymentMode' => 'Mode de paiement',
    'dashboardSelfpickupOrders' => 'Commandes d\'emporté',
    'dashboardOngoingDeliveries' => 'Livraisons en cours',
    'seNoStorePaymentGatewayMessage' => 'Aucune passerelle de paiement active.Les passerelles de paiement sélectionnées par l\'administrateur seront héritées.',
    'seLblSelectPaymentGateways' => 'Sélectionnez les passerelles de paiement',

    /*Version 2.4.0 */
    'navDashboard' => 'Tableau de bord',
    'zenMode' => 'Zen Mode [Beta]',
    'ovPaidWithWallet' => 'Payé avec',
    'ovSubTotal' => 'Sous-Total',
    'ovPayable' => 'Payable',
    'ovOrderType' => 'typeDeCommande',
    'ovOrderTypeDelivery' => 'Livraison',
    'ovOrderTypeSelfPickup' => 'Emporté',
    'ovStatusText' => 'STATUS',

    'payoutAccountDetailsTitle' => 'Détails du compte de paiement',
    'bankNameLabel' => 'Nom de banque',
    'bankCodeLabel' => 'Code banque/IFSC',
    'recipientNameLabel' => 'Nom du destinataire',
    'accountNumberLabel' => 'Numéro de compte',
    'paypalIdLabel' => 'Paypal ID',
    'upiIDLabel' => 'UPI ID',

    /* New Addon Category Page */
    'addonCategoryPageTitle' => 'Add Addon Category',
    'addonCategoryBlockTitle' => 'New Addon Category',
    'newAddonCategoryNameLabel' => 'Nom:',
    'newAddonCategoryTypeLabel' => 'Type',
    'newAddonCategoryDescriptionLabel' => 'Description:',
    'newAddonCategoryDescriptionPlaceholder' => 'Description courte (50-80 caractères)',
    'newAddonCategoryDescriptionSubTitle' => 'Cela sera affiché dans la page d\'articles lors de la sélection des catégories complémentaires',
    'newAddonCategoryAddAddonButton' => 'Add Addon',
    'newAddonCategoryAddonsBlockTitle' => 'Addons',
    'newAddonCategoryAddonPlaceholderName' => 'Addon Name',
    'newAddonCategoryAddonPlaceholderPrice' => 'Addon Price',
    'newAddonCategoryAddonRemove' => 'Remove Addon',
    /* END New Addon Category Page */

    /* Version 2.5.0 */
    'storeDeliveryTypeLabel' => 'type de livraison',
    'storeDeliveryTypeDeliveryOption' => 'Livraison',
    'storeDeliveryTypeSelfPickupOption' => 'Emporté',
    'storeDeliveryTypeBothOption' => 'Livraison et Emporté',

    'fileSectionNoFileSelected' => 'Aucun fichier sélectionné',
    'fileSectionChooseFileButton' => 'Choisir le fichier',

    'storeLatitudeFieldPlaceholder' => 'Latitude du magasin',
    'storeLongitudeFieldPlaceholder' => 'Longitude du magasin',

    'closeStoreToolTipMessage' => 'Les utilisateurs ne pourront pas passer de commande dans ce magasin s\'il est fermé',
    'openStoreToolTipMessage' => 'Le magasin est fermé. Ouvrez pour accepter les commandes.',

    'editItemCategoryName' => 'Modifier la catégorie de menu',

];
